-- 更新订单状态枚举，添加 APPROVED 状态
-- 执行此脚本前请备份数据库

ALTER TABLE `service_order` 
MODIFY COLUMN `status` ENUM('PENDING', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED') 
NOT NULL DEFAULT 'PENDING' 
COMMENT '订单状态：PENDING-待审核, APPROVED-已审核待派单, IN_PROGRESS-进行中, COMPLETED-已完成, CANCELLED-已取消';
